// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIn8ZCR_1Kg6NlTmWLd7Ggsx_dqNlk8KY',
    appId: '1:140202034942:web:b965cd4e5ffefb4f6d87af',
    messagingSenderId: '140202034942',
    projectId: 'chatapp-19b5c',
    authDomain: 'chatapp-19b5c.firebaseapp.com',
    storageBucket: 'chatapp-19b5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKqJjdk_VBKVtwE4ulKrPpsGp52Zd0pAQ',
    appId: '1:140202034942:android:b8de06b3f91a4aa26d87af',
    messagingSenderId: '140202034942',
    projectId: 'chatapp-19b5c',
    storageBucket: 'chatapp-19b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjU4GmMQ3GBN1resmABc6Pd9mtltXmF9I',
    appId: '1:140202034942:ios:5947eca3772f5c806d87af',
    messagingSenderId: '140202034942',
    projectId: 'chatapp-19b5c',
    storageBucket: 'chatapp-19b5c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjU4GmMQ3GBN1resmABc6Pd9mtltXmF9I',
    appId: '1:140202034942:ios:5947eca3772f5c806d87af',
    messagingSenderId: '140202034942',
    projectId: 'chatapp-19b5c',
    storageBucket: 'chatapp-19b5c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIn8ZCR_1Kg6NlTmWLd7Ggsx_dqNlk8KY',
    appId: '1:140202034942:web:530e646870fe29716d87af',
    messagingSenderId: '140202034942',
    projectId: 'chatapp-19b5c',
    authDomain: 'chatapp-19b5c.firebaseapp.com',
    storageBucket: 'chatapp-19b5c.appspot.com',
  );
}
